/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmatrix.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 22, 2025
 *  time:  1:30:10 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/
/* Empty file, no matrix support functions are needed for this model */


