/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  EulerAngles.c
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 22, 2025
 *  time:  1:27:43 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/*****************************************************************************
--------------------------------------------------------------------------

 Copyright � 1995-2007 Controllab Products B.V. All Rights Reserved.

             www.controllab.nl
               www.20sim.com

 Authors: Frank Groen
--------------------------------------------------------------------------
 Description:

 Contains code for converting between different angle representations
 all 24 different kind of Euler angles
 Quaternions and H-Matrices and Rotation Matrices
--------------------------------------------------------------------------
******************************************************************************/

