# TCL File Generated by Component Editor 24.1
# Wed Apr 30 11:02:48 CEST 2025
# DO NOT MODIFY


# 
# quad_enc "quad_enc" v1.0
#  2025.04.30.11:02:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module quad_enc
# 
set_module_property DESCRIPTION ""
set_module_property NAME quad_enc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME quad_enc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL quad_enc
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file quad_enc.v VERILOG PATH src/quad_enc.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter COUNTER_WIDTH INTEGER 16
set_parameter_property COUNTER_WIDTH DEFAULT_VALUE 16
set_parameter_property COUNTER_WIDTH DISPLAY_NAME COUNTER_WIDTH
set_parameter_property COUNTER_WIDTH TYPE INTEGER
set_parameter_property COUNTER_WIDTH UNITS None
set_parameter_property COUNTER_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point counter
# 
add_interface counter conduit end
set_interface_property counter associatedClock clock
set_interface_property counter associatedReset ""
set_interface_property counter ENABLED true
set_interface_property counter EXPORT_OF ""
set_interface_property counter PORT_NAME_MAP ""
set_interface_property counter CMSIS_SVD_VARIABLES ""
set_interface_property counter SVD_ADDRESS_GROUP ""

add_interface_port counter counter count Output "((COUNTER_WIDTH-1)) - (0) + 1"


# 
# connection point channel_a
# 
add_interface channel_a conduit end
set_interface_property channel_a associatedClock clock
set_interface_property channel_a associatedReset ""
set_interface_property channel_a ENABLED true
set_interface_property channel_a EXPORT_OF ""
set_interface_property channel_a PORT_NAME_MAP ""
set_interface_property channel_a CMSIS_SVD_VARIABLES ""
set_interface_property channel_a SVD_ADDRESS_GROUP ""

add_interface_port channel_a channel_a signal Input 1


# 
# connection point channel_b
# 
add_interface channel_b conduit end
set_interface_property channel_b associatedClock clock
set_interface_property channel_b associatedReset ""
set_interface_property channel_b ENABLED true
set_interface_property channel_b EXPORT_OF ""
set_interface_property channel_b PORT_NAME_MAP ""
set_interface_property channel_b CMSIS_SVD_VARIABLES ""
set_interface_property channel_b SVD_ADDRESS_GROUP ""

add_interface_port channel_b channel_b signal Input 1

