# TCL File Generated by Component Editor 24.1
# Tue May 06 16:22:51 CEST 2025
# DO NOT MODIFY


# 
# quad_comm "quad_comm" v1.0
#  2025.05.06.16:22:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module quad_comm
# 
set_module_property DESCRIPTION ""
set_module_property NAME quad_comm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME quad_comm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bus_comm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bus_comm.v VERILOG PATH src/bus_comm.v TOP_LEVEL_FILE
add_fileset_file quad_enc.v VERILOG PATH src/quad_enc.v


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter COUNTER_WIDTH INTEGER 16
set_parameter_property COUNTER_WIDTH DEFAULT_VALUE 16
set_parameter_property COUNTER_WIDTH DISPLAY_NAME COUNTER_WIDTH
set_parameter_property COUNTER_WIDTH TYPE INTEGER
set_parameter_property COUNTER_WIDTH UNITS None
set_parameter_property COUNTER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COUNTER_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_address address Input 8
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_readdata readdata Output "((DATA_WIDTH-1)) - (0) + 1"
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_writedata writedata Input "((DATA_WIDTH-1)) - (0) + 1"
add_interface_port slave slave_byteenable byteenable Input "(((DATA_WIDTH/8)-1)) - (0) + 1"
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point pitch_channel_a
# 
add_interface pitch_channel_a conduit end
set_interface_property pitch_channel_a associatedClock clock
set_interface_property pitch_channel_a associatedReset ""
set_interface_property pitch_channel_a ENABLED true
set_interface_property pitch_channel_a EXPORT_OF ""
set_interface_property pitch_channel_a PORT_NAME_MAP ""
set_interface_property pitch_channel_a CMSIS_SVD_VARIABLES ""
set_interface_property pitch_channel_a SVD_ADDRESS_GROUP ""

add_interface_port pitch_channel_a pitch_channel_a signal Input 1


# 
# connection point pitch_channel_b
# 
add_interface pitch_channel_b conduit end
set_interface_property pitch_channel_b associatedClock clock
set_interface_property pitch_channel_b associatedReset ""
set_interface_property pitch_channel_b ENABLED true
set_interface_property pitch_channel_b EXPORT_OF ""
set_interface_property pitch_channel_b PORT_NAME_MAP ""
set_interface_property pitch_channel_b CMSIS_SVD_VARIABLES ""
set_interface_property pitch_channel_b SVD_ADDRESS_GROUP ""

add_interface_port pitch_channel_b pitch_channel_b signal Input 1


# 
# connection point yaw_channel_a
# 
add_interface yaw_channel_a conduit end
set_interface_property yaw_channel_a associatedClock clock
set_interface_property yaw_channel_a associatedReset ""
set_interface_property yaw_channel_a ENABLED true
set_interface_property yaw_channel_a EXPORT_OF ""
set_interface_property yaw_channel_a PORT_NAME_MAP ""
set_interface_property yaw_channel_a CMSIS_SVD_VARIABLES ""
set_interface_property yaw_channel_a SVD_ADDRESS_GROUP ""

add_interface_port yaw_channel_a yaw_channel_a signal Input 1


# 
# connection point yaw_channel_b
# 
add_interface yaw_channel_b conduit end
set_interface_property yaw_channel_b associatedClock clock
set_interface_property yaw_channel_b associatedReset ""
set_interface_property yaw_channel_b ENABLED true
set_interface_property yaw_channel_b EXPORT_OF ""
set_interface_property yaw_channel_b PORT_NAME_MAP ""
set_interface_property yaw_channel_b CMSIS_SVD_VARIABLES ""
set_interface_property yaw_channel_b SVD_ADDRESS_GROUP ""

add_interface_port yaw_channel_b yaw_channel_b signal Input 1

