/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  PositionControllerTilt.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 22, 2025
 *  time:  1:27:43 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file defines a framework for a 20-sim dynamic DLL */

/* system include files */
#include <windows.h>

/* 20-sim include files */
#include "xxmodel.h"

/* 20-sim defines */
#define DllExport __declspec( dllexport )

/* 20-sim typedefs */
typedef struct
{
	double versionNumber;
	int nrInputs;
	int nrOutputs;
	int nrIndepStates;
	int nrDepStates;
	int nrAlgLoops;
	double simulationStartTime;
	double simulationFinishTime;
	double simulationCurrentTime;
	BOOL major;
	BOOL initialOutputCalculation;
} SimulatorSFunctionStruct;

/* the submodel io variables */
XXInteger xx_number_of_inputs = 3;
XXInteger xx_number_of_outputs = 1;

/* the names of the submodel io variables 
XXString xx_input_names[] = {
	"corr",
	"in",
	"position"
,	NULL
};
XXString xx_output_names[] = {
	"out"
,	NULL
};
*/

/* this function sets the input variables from the input vector */
void XXCopyInputsToVariables (XXDouble *u)
{

	/* copy the input vector to the input variables */
	xx_V[8] = u[0];		/* corr */
	xx_V[9] = u[1];		/* in */
	xx_V[10] = u[2];		/* position */

}

/* this function uses the output variables to fill the output vector */
void XXCopyVariablesToOutputs (XXDouble *y)
{
	/* copy the output variables to the output vector */
	y[0] = 	xx_V[11];		/* out */


}


/* this function is called when the simulator initializes the DLL
   on initialization the following fields must be filed in:
 		nrIndepStates
 		nrDepStates
 		nrAlgLoop
   the following fields already have valid values:
   		simulationStartTime
   		simulationFinishTime
   		simulationCurrentTime
   the number of inputs and outputs must match with the 20-sim model
   		nrInputs
   		nrOutputs
*/
DllExport int SFunctionInit(SimulatorSFunctionStruct *simStruct)
{
	/* do initialization of the parameters and initial values */
	XXModelInitialize();
	XXCalculateInitial();

	/* fill the simulator structure */
	simStruct->nrInputs = 3;
	simStruct->nrOutputs = 1;
	simStruct->nrIndepStates = 3;
	simStruct->nrDepStates = 0;
	simStruct->nrAlgLoops = 0;

	/* return the success */
	return 1;
}

/* The initial value for the independent states, dependent
   rates and algebraic loop variables can be specified by
   the DLL in this function. It is just called before the
   initial output calculation function. If all
   the initial values are zero, nothing has to be specified.
*/
DllExport int SFunctionGetInitialStates(double *initialIndepStates, double * initialDepRates,
							  double *initialAlgloopIn, SimulatorSFunctionStruct *simStruct)
{
	/* copy our initial states to the given states. */
	memcpy(initialIndepStates, xx_s, simStruct->nrIndepStates * sizeof(double));
	xx_major = simStruct->major;

	XXCalculateInitial();
	XXCalculateStatic();

	/* calculate the model */
	XXCalculateInput ();
	XXCalculateDynamic ();
	XXCalculateOutput ();

	/* return the success */
	return 1;
}


/* It is possible that the DLL-function can give an initial output.
   A separate function is called so that the DLL can calculate it's
   initial output values. The boolean initialOutputCalculation in
   the simulatorSFunction structure is used.
   Here all the fields of the SimulatorSFunctionStruct are input for
   the function. The inputArray, stateArray, outputArray and rateArray
   are always given as arguments of the function. Dependent on the
   number of dependent states and algebraic loop variables more
   arguments can be given as shown in the functions below
   (sFunctionName is the name defined by the parameter name specified
   by the user):
*/
DllExport int SFunctionCalculate(double *inputArray, double *stateArray, double *outputArray,
				  double *rateArray, SimulatorSFunctionStruct *simStruct)
{
	/* first copy the supplied inputs to our inputs */
	XXCopyInputsToVariables(inputArray);

	/* copy the given states to our states */
	memcpy(xx_s, stateArray, simStruct->nrIndepStates * sizeof(double));
	xx_major = simStruct->major;

	/* set the simulation time on the give time */
	xx_time = simStruct->simulationCurrentTime;;

	/* are we at the begin of the simulation ? */
	if( simStruct->simulationCurrentTime == simStruct->simulationStartTime )
	{
		/* initial and static calculation at the begin */
		XXCalculateInitial();
		XXCalculateStatic();
	}

	/* calculate the model */
	XXCalculateInput ();
	XXCalculateDynamic ();
	XXCalculateOutput ();

	/* at the end of the simulation ? */
	if(	simStruct->major &&
		(simStruct->simulationCurrentTime >= simStruct->simulationFinishTime ) )
	{
		/* final calculations at the end */
		XXCalculateFinal();
	}

	/* copy the calculated rates to the rate array */
	memcpy(rateArray, xx_R, simStruct->nrIndepStates * sizeof(double));

	/* copy our outputs to the given outputs */
	XXCopyVariablesToOutputs(outputArray);

	/* return the success */
	return 1;
}

/* called at the beginning of a simulation */
DllExport int Initialize()
{
	/* return the success */
	return 0;
}

/* termination of the simulation run */
DllExport int Terminate()
{
	/* return the success */
	return 0;
}

/* the main entry point of the DLL */
BOOL WINAPI DllMain (HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
	/* return the success */
    return TRUE;
}


