/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.c
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 22, 2025
 *  time:  1:27:43 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   XXDouble xx_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   XXString xx_variable_names[] = {
	 VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void XXCalculateOutput (void)
   {
	 OUTPUT_EQUATIONS
	 ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>
#include <string.h>

/* 20-sim include files */
#include "xxmodelTilt.h"
#include "xxfuncs.h"

/* the global variables */
XXDouble tilt_xx_start_time = 0.0;
XXDouble tilt_xx_finish_time = 20.0;
XXDouble tilt_xx_step_size = 0.01;
XXDouble tilt_xx_time = 0.0;
XXInteger tilt_xx_steps = 0;
XXBoolean tilt_xx_initialize = XXTRUE;
XXBoolean tilt_xx_major = XXTRUE;
XXBoolean tilt_xx_stop_simulation = XXFALSE;

/* the variable arrays */
XXDouble tilt_xx_P[tilt_xx_parameters_size];	/* parameters */
XXDouble tilt_xx_I[tilt_xx_initialvalues_size]; /* initial values */
XXDouble tilt_xx_V[tilt_xx_variables_size];		/* variables */
XXDouble tilt_xx_s[tilt_xx_states_size];		/* states */
XXDouble tilt_xx_R[tilt_xx_states_size];		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
XXString xx_parameter_names[] = {
	"corrGain\\K",
	"PID1\\kp",
	"PID1\\tauD",
	"PID1\\beta",
	"PID1\\tauI",
	"SignalLimiter2\\minimum",
	"SignalLimiter2\\maximum"
,	NULL
};
XXString xx_initial_value_names[] = {
	"PID1\\uD_previous_initial",
	"PID1\\error_previous_initial",
	"PID1\\uI_previous_initial"
,	NULL
};
XXString xx_variable_names[] = {
	"corrGain\\input",
	"corrGain\\output",
	"PID1\\output",
	"",
	"PlusMinus1\\output",
	"PlusMinus2\\plus1",
	"PlusMinus2\\minus1",
	"SignalLimiter2\\output",
	"corr",
	"in",
	"position",
	"out"
,	NULL
};
XXString xx_state_names[] = {
	"PID1\\uD_previous",
	"PID1\\error_previous",
	"PID1\\uI_previous"
,	NULL
};
XXString xx_rate_names[] = {
	"",
	"PID1\\error",
	""
,	NULL
};
*/

#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
void tilt_XXModelInitialize_parameters(void)
{
	/* set the parameters */
	tilt_xx_P[0] = 0.0;	  /* corrGain\K */
	tilt_xx_P[1] = 1.6;	  /* PID1\kp */
	tilt_xx_P[2] = 0.05;	  /* PID1\tauD */
	tilt_xx_P[3] = 0.001;  /* PID1\beta */
	tilt_xx_P[4] = 10.5;	  /* PID1\tauI */
	tilt_xx_P[5] = -0.99; /* SignalLimiter2\minimum */
	tilt_xx_P[6] = 0.99;  /* SignalLimiter2\maximum */
}
#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

void tilt_XXModelInitialize_initialvalues(void)
{
	/* set the initial values */
	tilt_xx_I[0] = 0.0; /* PID1\uD_previous_initial */
	tilt_xx_I[1] = 0.0; /* PID1\error_previous_initial */
	tilt_xx_I[2] = 0.0; /* PID1\uI_previous_initial */
}

void tilt_XXModelInitialize_states(void)
{
	/* set the states */
	tilt_xx_s[0] = tilt_xx_I[0]; /* PID1\uD_previous */
	tilt_xx_s[1] = tilt_xx_I[1]; /* PID1\error_previous */
	tilt_xx_s[2] = tilt_xx_I[2]; /* PID1\uI_previous */
}

void tilt_XXModelInitialize_variables(void)
{
	/* initialize the variable memory to zero */
	memset(tilt_xx_V, 0, tilt_xx_variables_size * sizeof(XXDouble));
}

/* this method is called before calculation is possible */
void tilt_XXModelInitialize(void)
{
	tilt_XXModelInitialize_parameters();
	tilt_XXModelInitialize_variables();
	tilt_XXModelInitialize_initialvalues();
	tilt_XXModelInitialize_states();
}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void tilt_XXCalculateInitial(void)
{

	/* set the states again, they might have changed in the initial calculation */
	tilt_XXModelInitialize_states();
}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void tilt_XXCalculateStatic(void)
{
}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void tilt_XXCalculateInput(void)
{
}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void tilt_XXCalculateDynamic(void)
{
	/* PID1\factor = 1 / (sampletime + PID1\tauD * PID1\beta); */
	tilt_xx_V[3] = 1.0 / (tilt_xx_step_size + tilt_xx_P[2] * tilt_xx_P[3]);

	/* corrGain\input = corr; */
	tilt_xx_V[0] = tilt_xx_V[8];

	/* PlusMinus2\plus1 = in; */
	tilt_xx_V[5] = tilt_xx_V[9];

	/* PlusMinus2\minus1 = position; */
	tilt_xx_V[6] = tilt_xx_V[10];

	/* corrGain\output = corrGain\K * corrGain\input; */
	tilt_xx_V[1] = tilt_xx_P[0] * tilt_xx_V[0];

	/* PID1\error = PlusMinus2\plus1 - PlusMinus2\minus1; */
	tilt_xx_R[1] = tilt_xx_V[5] - tilt_xx_V[6];

	/* PID1\uD = PID1\factor * (((PID1\tauD * PID1\uD_previous) * PID1\beta + (PID1\tauD * PID1\kp) * (PID1\error - PID1\error_previous)) + (sampletime * PID1\kp) * PID1\error); */
	tilt_xx_R[0] = tilt_xx_V[3] * (((tilt_xx_P[2] * tilt_xx_s[0]) * tilt_xx_P[3] + (tilt_xx_P[2] * tilt_xx_P[1]) * (tilt_xx_R[1] - tilt_xx_s[1])) + (tilt_xx_step_size * tilt_xx_P[1]) * tilt_xx_R[1]);

	/* PID1\uI = PID1\uI_previous + (sampletime * PID1\uD) / PID1\tauI; */
	tilt_xx_R[2] = tilt_xx_s[2] + (tilt_xx_step_size * tilt_xx_R[0]) / tilt_xx_P[4];

	/* PID1\output = PID1\uI + PID1\uD; */
	tilt_xx_V[2] = tilt_xx_R[2] + tilt_xx_R[0];

	/* PlusMinus1\output = corrGain\output + PID1\output; */
	tilt_xx_V[4] = tilt_xx_V[1] + tilt_xx_V[2];

	/* SignalLimiter2\output = if PlusMinus1\output < SignalLimiter2\minimum... ; */
	tilt_xx_V[7] = ((tilt_xx_V[4] < tilt_xx_P[5]) ?
												  /* SignalLimiter2\minimum */
						tilt_xx_P[5]
												  :
												  /* if PlusMinus1\output > SignalLimiter2\maximum...  */
						((tilt_xx_V[4] > tilt_xx_P[6]) ?
													   /* SignalLimiter2\maximum */
							 tilt_xx_P[6]
													   :
													   /* PlusMinus1\output */
							 tilt_xx_V[4]));

	/* increment the step counter */
	tilt_xx_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void tilt_XXCalculateOutput(void)
{
	/* out = SignalLimiter2\output; */
	tilt_xx_V[11] = tilt_xx_V[7];
}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void tilt_XXCalculateFinal(void)
{
}

/* this method is called after all calculations are performed */
void tilt_XXModelTerminate(void)
{
}
