/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 22, 2025
 *  time:  1:27:43 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_MODELTILT_H
#define XX_MODELTILT_H

/* Our own include files */
#include "xxtypes.h"

/* Simulation variables */
extern XXDouble tilt_xx_start_time;
extern XXDouble tilt_xx_finish_time;
extern XXDouble tilt_xx_step_size;
extern XXDouble tilt_xx_time;
extern XXInteger tilt_xx_steps;
extern XXBoolean tilt_xx_initialize;
extern XXBoolean tilt_xx_major;
extern XXBoolean tilt_xx_stop_simulation;

/* Model size constants */
#define tilt_xx_constants_size 0
#define tilt_xx_parameters_size 7
#define tilt_xx_initialvalues_size 3
#define tilt_xx_variables_size 12
#define tilt_xx_states_size 3

/* Variable arrays */
extern XXDouble tilt_xx_P[];
extern XXDouble tilt_xx_I[];
extern XXDouble tilt_xx_V[];
extern XXDouble tilt_xx_s[];
extern XXDouble tilt_xx_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern XXString xx_parameter_names[];
extern XXString xx_initial_value_names[];
extern XXString xx_variable_names[];
extern XXString xx_state_names[];
extern XXString xx_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void tilt_XXModelInitialize (void);
/* Initialize specific model values */
void tilt_XXModelInitialize_parameters(void);
void tilt_XXModelInitialize_initialvalues(void);
void tilt_XXModelInitialize_states(void);
void tilt_XXModelInitialize_variables(void);
void tilt_XXModelTerminate (void);

/* Computation methods */
void tilt_XXCalculateInitial (void);
void tilt_XXCalculateStatic (void);
void tilt_XXCalculateInput (void);
void tilt_XXCalculateDynamic (void);
void tilt_XXCalculateOutput (void);
void tilt_XXCalculateFinal (void);


#endif

