/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.h
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 22, 2025
 *  time:  1:30:10 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_MODELPAN_H
#define XX_MODELPAN_H

/* Our own include files */
#include "xxtypes.h"

/* Simulation variables */
extern XXDouble pan_xx_start_time;
extern XXDouble pan_xx_finish_time;
extern XXDouble pan_xx_step_size;
extern XXDouble pan_xx_time;
extern XXInteger pan_xx_steps;
extern XXBoolean pan_xx_initialize;
extern XXBoolean pan_xx_major;
extern XXBoolean pan_xx_stop_simulation;

/* Model size constants */
#define pan_xx_constants_size 0
#define pan_xx_parameters_size 7
#define pan_xx_initialvalues_size 3
#define pan_xx_variables_size 10
#define pan_xx_states_size 3

/* Variable arrays */
extern XXDouble pan_xx_P[];
extern XXDouble pan_xx_I[];
extern XXDouble pan_xx_V[];
extern XXDouble pan_xx_s[];
extern XXDouble pan_xx_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern XXString xx_parameter_names[];
extern XXString xx_initial_value_names[];
extern XXString xx_variable_names[];
extern XXString xx_state_names[];
extern XXString xx_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void pan_XXModelInitialize (void);
/* Initialize specific model values */
void pan_XXModelInitialize_parameters(void);
void pan_XXModelInitialize_initialvalues(void);
void pan_XXModelInitialize_states(void);
void pan_XXModelInitialize_variables(void);
void pan_XXModelTerminate (void);

/* Computation methods */
void pan_XXCalculateInitial (void);
void pan_XXCalculateStatic (void);
void pan_XXCalculateInput (void);
void pan_XXCalculateDynamic (void);
void pan_XXCalculateOutput (void);
void pan_XXCalculateFinal (void);


#endif

